project:
  type: website
  output-dir: docs
  

website:
  title: "Yichen Ji"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



